version: '2'
services:
    kundel-app:
        image: kundel
        external_links:
            - kundel-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Kundel
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kundel-mongodb:
        extends:
            file: mongodb.yml
            service: kundel-mongodb
