version: '2'
services:
    kundel-mongodb:
        container_name: kundel-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/Kundel/mongodb/:/data/db/
